# Generated by Django 5.0.6 on 2024-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snp_site_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
        migrations.AlterField(
            model_name='chromosome',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='image_file',
            field=models.ImageField(upload_to='snp_site/uploads/'),
        ),
    ]
