# Generated by Django 5.0.6 on 2024-07-04 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snp_site_app', '0002_alter_species_options_alter_chromosome_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snp',
            name='maf',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.49)]),
        ),
    ]
