# Generated by Django 5.0.6 on 2024-07-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snp_site_app', '0003_alter_snp_maf'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromosome',
            name='name',
            field=models.CharField(default='unspecified', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chromosome',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='snp',
            name='annotations',
            field=models.TextField(),
        ),
    ]
